apiVersion: v1
kind: Service
metadata:
  name: purchaseswebservice
  labels:
    example: purchaseswebservice
  annotations:
    auth.istio.io/8017: NONE
spec:
  ports:
  - name: http
    port: 8017
  selector:
    example: purchaseswebservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: purchaseswebservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        example: purchaseswebservice
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: tomaszmi/hackaton-kyma-spartacus-microservice
        imagePullPolicy: Always
        name: purchaseswebservice
        ports:
        - name: http
          containerPort: 8017
